### ISSUE TITLE
numpy-vendor needs python 3.5

### ISSUE THREAD

**Issue by charris** [numpy/numpy-vendor#6]
python 3.5 has been released and we should support it.

**Comment by rgommers** [comment]
MinGW32 doesn't support the universal MSVC runtime (see http://stevedower.id.au/blog/building-for-python-3-5/) and never will, so I don't think there's a point to add 3.5 to numpy-vendor.

MinGW-W64 doesn't support it either yet, but very likely will do so at some point. Until that happens, I think our only choices are no official binaries or MSVC-built ones.

@carlk @cournape @juliantaylor please correct me if I'm wrong.

**Comment by certik** [comment]
I was wondering if we can use Appveyor to build the binaries automatically using MSVC. Is there any advantage of using MinGW32 or MinGW-W64 on Windows? Apart from the compilers being open source, so that people can use them locally, as opposed on services like Appveyor, let's say.

**Comment by rgommers** [comment]
@ogrisel spent quite some time trying to get Numpy to build on Appveyor, but ran into build time and OpenBLAS issues: https://github.com/numpy/numpy/pull/5328

I suspect nothing has changed since then that warrants trying again now.

**Comment by ogrisel** [comment]
> @ogrisel spent quite some time trying to get Numpy to build on Appveyor, but ran into build time and OpenBLAS issues: numpy/numpy#5328

I did not try very hard though. Someone familiar with windows and numpy might get it to work.

However mingw's gfortran is required for scipy at least because there is no fortran compiler part of the MS toolchain.

**Comment by certik** [comment]
For Appveyor, one has to essentially prebuild all binaries (like openblas), put the binaries in some repository (let's say numpy-vendor into a branch `binaries`) and then just download them. For example. for SymEngine, we build it on Appveyor with all MSVC, MinGW32 and MinGW-W64, and link against the GMP library: https://ci.appveyor.com/project/certik/symengine/build/221, and it's been very robust and reliable.

**Comment by rgommers** [comment]
We've got Appveyor builds now, so closing. Thanks all.
